### ISSUE TITLE
'float' object has no attribute 'shape'

### ISSUE THREAD

**Issue by youka123** [peterdsharpe/transport-aircraft#2]
I encountered an issue while running the study_tank_gravimetric_efficiency.py file and received the following error message:

**File ~/anaconda3/lib/python3.10/site-packages/AeroSandbox-4.0.9-py3.10.egg/aerosandbox/optimization/opti.py:606 in solve
    size_k = np.product(k.shape)
AttributeError: 'float' object has no attribute 'shape'**

The error occurs in the opti.py file at line 606 while processing this particular section of the code.

Could you clarify the expected type and properties of the variable k at that specific point in the code?（or if possible, would be appreciate if you could provide a solution to fix this issue.)

Other question in In study_tank_gravimetric_efficiency.py, should the sixth line **vals = np.sinspace(0.2221, 1, 21)[::-1]** be modified to **vals = np.linspace(0.2221, 1, 21)[::-1]**?

**Comment by peterdsharpe** [comment]
Hey @youka123 !

-----

Ah yes, so, regarding Question 1:

It looks like when we changed `design_opt.py` such that the "default" fuel was kerosene instead of LH2, we forgot to wrap `fuel_tank_gravimetric_efficiency` in an `opti.parameter()`, which allows it to be swept over.

To fix this, I've split this study into its own folder called `study_tank_gravimetric_efficiency`, which is available in this repository as of this commit: 5604cf76d5f7f75f8cc16c9ed96fa97a96113919

Apologies for this - my personal file-naming convention is that any files prefixed with `study_` are kind of one-off studies, so less well-supported.

Now when you run it, you should get:
![image](https://github.com/peterdsharpe/transport-aircraft/assets/6295985/8aaf3bc2-dace-4a14-b030-5b8edfd2fc84)


-----

Re: Question 2:

Yes, this is intended. `np.sinspace` fulfills the same function as `np.linspace`, but uses what is sometimes called "sine spacing". A more mathematically-rigorous way to define "sine spacing" is that it is half of a [Chebyshev-node spacing distribution](https://en.wikipedia.org/wiki/Chebyshev_nodes) - "sine spacing" is just the aerospace standard name for it, for some reason.

![image](https://github.com/peterdsharpe/transport-aircraft/assets/6295985/c8d722d1-ad72-4560-aec1-648b6327094b)

The reason we do this here is that we expect there to be a lot more performance variation near the low end of the gravimetric efficiency range (0.02221) than near the top of it (1). So, this will sample the space more densely near the region of high variation.
